// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepPSP3VHYXlxXsWu04tMihVDG-xUBjp4',
    appId: '1:240897979609:web:8d6da3452d65f518963ac8',
    messagingSenderId: '240897979609',
    projectId: 'barbanter-c107d',
    authDomain: 'barbanter-c107d.firebaseapp.com',
    storageBucket: 'barbanter-c107d.firebasestorage.app',
    measurementId: 'G-WPHWTCWTFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkNc7Yx2fvct2uHlkRN9wZLhYwaEKy_c',
    appId: '1:240897979609:android:be2a07cfe5bcb2a4963ac8',
    messagingSenderId: '240897979609',
    projectId: 'barbanter-c107d',
    storageBucket: 'barbanter-c107d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPPbmuipCOARCqxyfMOlBGLkVUoJ5Aec8',
    appId: '1:240897979609:ios:dbc4107ff5c2a344963ac8',
    messagingSenderId: '240897979609',
    projectId: 'barbanter-c107d',
    storageBucket: 'barbanter-c107d.firebasestorage.app',
    iosBundleId: 'com.BarBanter.WV93Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPPbmuipCOARCqxyfMOlBGLkVUoJ5Aec8',
    appId: '1:240897979609:ios:c71b5da8cac0ff35963ac8',
    messagingSenderId: '240897979609',
    projectId: 'barbanter-c107d',
    storageBucket: 'barbanter-c107d.firebasestorage.app',
    iosBundleId: 'com.example.favoriteBars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAepPSP3VHYXlxXsWu04tMihVDG-xUBjp4',
    appId: '1:240897979609:web:8b66433474b5f7b7963ac8',
    messagingSenderId: '240897979609',
    projectId: 'barbanter-c107d',
    authDomain: 'barbanter-c107d.firebaseapp.com',
    storageBucket: 'barbanter-c107d.firebasestorage.app',
    measurementId: 'G-C4J0N0QGVJ',
  );
}
